"""dodanie tabeli security i polaczenie jej z tabela user

Revision ID: 1719596c9621
Revises: ad3a1dfe9d4b
Create Date: 2023-11-10 16:25:18.896359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1719596c9621'
down_revision = 'ad3a1dfe9d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('two_fa', sa.Boolean(), nullable=True),
    sa.Column('activity_log', sa.Boolean(), nullable=True),
    sa.Column('email_code', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('two_fa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_fa', sa.INTEGER(), nullable=True))

    op.drop_table('security')
    # ### end Alembic commands ###
