"""dodanie login_code dla kodu logowania uzytkownika

Revision ID: b3bef6f1345b
Revises: e9813104d430
Create Date: 2023-11-14 16:35:12.207770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3bef6f1345b'
down_revision = 'e9813104d430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_code', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('login_code')

    # ### end Alembic commands ###
