"""login_session_count

Revision ID: e48988f41405
Revises: 
Create Date: 2023-12-19 22:43:59.168667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e48988f41405'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_session_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security', schema=None) as batch_op:
        batch_op.drop_column('login_session_count')

    # ### end Alembic commands ###
