"""dodanie email confirmation

Revision ID: e9813104d430
Revises: 1719596c9621
Create Date: 2023-11-12 21:54:58.927034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9813104d430'
down_revision = '1719596c9621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint('unique_confirmation_code', ['confirmation_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email_confirmed')
        batch_op.drop_column('confirmation_code')

    # ### end Alembic commands ###
